<a href="https://colab.research.google.com/github/callezenwaka/machine-learning/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set up

In [2]:
import numpy as np

In [3]:
np.random.seed(seed=1234)

# Basics

In [4]:
# scalar
x = np.array(6)
print("x: ", x)
print("x ndim: ", x.ndim) # number of dimensions
print("x shape: ", x.shape) # shape dimensions
print("x size: ", x.size) # size of elements
print("x dtype: ", x.dtype) # data type

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [5]:
# vector
x = np.array([1.3, 2.2, 1.7])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [6]:
# matrix
x = np.array([[1,2], [3,4], [5,6]])
print("x: \n", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x: 
 [[1 2]
 [3 4]
 [5 6]]
x ndim:  2
x shape:  (3, 2)
x size:  6
x dtype:  int64


In [7]:
# 3-D tensor
x = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("x: \n", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [8]:
# create tensors with built-in functions
print("np.zeros((2,2)): \n", np.zeros((2,2)))
print("np.ones((2,2)): \n", np.ones((2,2)))
print("np.eye((2)): \n", np.eye((2))) # identity matrix
print("np.random.random((2,2))\n", np.random.random((2,2)))

np.zeros((2,2)): 
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)): 
 [[1. 1.]
 [1. 1.]]
np.eye((2)): 
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2))
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


# Indexing

In [15]:
# indexing tensors
x = np.array([1,2,3])
print("x: ", x)
print("x[0]: ", x[0])
x[0] = 0
print("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [16]:
# slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("x:\n", x)
print("x column 1: ", x[:, 1])
print("x row 0: ", x[0, :])
print("x rows 0, 1 & cols 1, 2: \n", x[0:2, 1:3])

x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0, 1 & cols 1, 2: 
 [[2 3]
 [6 7]]


In [17]:
# integer array indexing
print("x: \n", x)
rows_to_get = np.array([0, 1, 2])
print("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print("cols_to_get: ", cols_to_get)
# combine sequences above to return values to get
print("Indexed values: ", x[rows_to_get, cols_to_get]) # (0,0), (1,2), (2,1)

x: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
Indexed values:  [ 1  7 10]


In [18]:
# boolean array indexing
x = np.array([[1,2], [3,4], [5,6]])
print("x:\n", x)
x = np.array([[1,2], [3,4], [5,6]])
print("x > 2:\n", x > 2)
print("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# Arithmetic

In [21]:
# basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print("x + y:\n", np.add(x, y)) # or x + y
print("x - y:\n", np.subtract(x, y)) # or x - y
print("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


# Dot Product

In [13]:
# dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # datatype ie: dtype, specified.
b = np.array([[7,8], [9,10], [11,12]], dtype=np.float64)
c = a.dot(b)
print(f"Input shape:\n{a.shape} · {b.shape} = {c.shape}")
print("Output:\n", c)

Input shape:
(2, 3) · (3, 2) = (2, 2)
Output:
 [[ 58.  64.]
 [139. 154.]]


# Axis Operations

In [16]:
# sum across a dimension
x = np.array([[1,2], [3,4]])
print("x:\n", x)
print("sum all:\n", np.sum(x)) # sum all elements
print("sum axis=0: ", np.sum(x, axis=0)) # sum across rows ie: top to bottom
print("sum axis=1: ", np.sum(x, axis=1)) # sum across column ie: left to right

x:
 [[1 2]
 [3 4]]
sum all:
 10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [20]:
# find minimum and maximum element, rows & columns
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("x:\n", x)
print("min. element: ", x.min())
print("max. element: ", x.max())
print("min. axis=0: ", x.min(axis=0)) # row
print("min. axis=1: ", x.min(axis=1)) # col
print("max. axis=0: ", x.max(axis=0)) # row
print("max. axis=1: ", x.max(axis=1)) # col

x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
min. element:  1
max. element:  9
min. axis=0:  [1 2 3]
min. axis=1:  [1 4 7]
max. axis=0:  [7 8 9]
max. axis=1:  [3 6 9]


# Broadcast

In [24]:
# broadcasting 
x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = np.add(x, y) # or x + y
print("z = x + y: ", z)

z = x + y:  [4 5]


# Transpose

In [28]:
# transposing
x = np.array([[1,2,3], [4,5,6]])
print("x:\n", x)
print("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print("y:\n", y)
print("y.shape ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]]
y.shape  (3, 2)


# Reshape

Reshaping

In [32]:
# reshaping
x = np.array([[1,2,3,4,5,6]])
print("x: ", x)
print("x.shape: ", x.shape)
y = np.reshape(x, (2,3))
print("y: \n", y)
print("y.shape: ", y.shape)
z = np.reshape(x, (2,-1))
print("z:\n", z)
print("z.shape: ", z.shape)

x:  [[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z:
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


high order reshaping

In [39]:
#
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
              [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print("x:\n", x)
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
y = np.transpose(x, (1,0,2))
print("\ny:\n", y)
print("y.shape", y.shape)
z = np.reshape(y, (y.shape[0], -1))
print("\nz:\n", z)
print("z.shape: ", z.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.ndim:  3
x.shape:  (2, 3, 4)

y:
 [[[ 1  1  1  1]
  [10 10 10 10]]

 [[ 2  2  2  2]
  [20 20 20 20]]

 [[ 3  3  3  3]
  [30 30 30 30]]]
y.shape (3, 2, 4)

z:
 [[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
z.shape:  (3, 8)


# Expanding / Reducing

Expanding

In [40]:
# adding dimensions
x = np.array([[1,2,3], [4,5,6]])
print("x:\n", x)
print("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # expand dim 1
print("y:\n", y)
print("y.shape: ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


Reducing

In [41]:
# removing dimensions
x = np.array([[[1,2,3]], [[4,5,6]]])
print("x:\n", x)
print("x.shape: ", x.shape)
y =np.squeeze(x, 1) # squeeze dim 1
print("y:\n", y)
print("y.shape: ", y.shape)

x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y:
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
